CREATE DATABASE workspace OWNER = 'jaredhz';

CREATE SCHEMA clients;
CREATE SCHEMA works;
CREATE SCHEMA employees;

CREATE TABLE clients.clientes(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(20) NOT NULL,
    ap_paterno VARCHAR(20) NOT NULL,
    ap_materno VARCHAR(20)
);

CREATE TABLE employees.empleados (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(20) NOT NULL,
    ap_paterno VARCHAR(20) NOT NULL,
    ap_materno VARCHAR(20),
    puesto TEXT
);

CREATE TABLE direcciones (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calle TEXT NOT NULL ,
    ciudad TEXT NOT NULL,
    estado TEXT NOT NULL,
    codigo_postal VARCHAR(5) NOT NULL
);

CREATE TABLE works.tareas (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    tarifa INT NOT NULL,
    horas_estimadas INT NOT NULL,
    numero_horas INT NOT NULL
);

CREATE TABLE works.coleccion_tareas (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE works.grupo_tareas(
    id_tarea INT NOT NULL REFERENCES works.tareas(id) ON DELETE CASCADE,
    id_coleccion_tareas INT NOT NULL REFERENCES works.coleccion_tareas(id) ON DELETE CASCADE,
    PRIMARY KEY(id_tarea, id_coleccion_tareas)
);

CREATE TABLE works.ordenes_de_trabajo(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT NOW(),
    fecha_requerida TIMESTAMP NOT NULL,
    fecha_termino TIMESTAMP NOT NULL,
    id_empleado INT NOT NULL REFERENCES employees.empleados(id) ON DELETE CASCADE,
    direccion INT NOT NULL REFERENCES direcciones(id) ON DELETE CASCADE,
    coleccion_tareas INT NOT NULL REFERENCES works.coleccion_tareas(id) ON DELETE CASCADE
);

CREATE TABLE  works.coleccion_de_trabajo (
    id_cliente INT NOT NULL REFERENCES clients.clientes(id) ON DELETE CASCADE,
    id_orden INT NOT NULL REFERENCES works.ordenes_de_trabajo(id) ON DELETE CASCADE,
    PRIMARY KEY(id_cliente, id_orden)
);

CREATE TABLE works.materiales(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    costo DECIMAL NOT NULL
);

CREATE TABLE works.ordenes_materiales(
    id_orden INT NOT NULL REFERENCES works.ordenes_de_trabajo(id) ON DELETE CASCADE,
    id_material INT NOT NULL REFERENCES works.materiales(id) ON DELETE CASCADE,
    PRIMARY KEY(id_orden, id_material)
);

ALTER TABLE clients.clientes ADD COLUMN direccion int;
ALTER TABLE clients.clientes ADD CONSTRAINT fk_direcciones FOREIGN KEY (direccion)
REFERENCES direcciones(id) ON UPDATE CASCADE ON DELETE RESTRICT;
CREATE INDEX fk1_direcciones ON clients.clientes (direccion);

ALTER TABLE employees.empleados ADD COLUMN direccion int;
ALTER TABLE employees.empleados ADD CONSTRAINT fk_direcciones_e FOREIGN KEY (direccion)
REFERENCES direcciones(id) ON UPDATE CASCADE ON DELETE RESTRICT;
CREATE INDEX fk1_direcciones_e ON employees.empleados (direccion);

ALTER TABLE works.tareas
ALTER COLUMN tarifa TYPE DECIMAL;